export const calculators = [
  {
    id: 'mass-mass',
    shortLabel: '% m/m',
    title: 'Porcentaje masa / masa',
    tagline: 'Relaciona la masa del soluto con la masa total de la solucion.',
    formula: '% m/m = (masa de soluto / masa de solucion) * 100',
    description: 'Se usa cuando el problema entrega masas y quiere expresar composicion relativa de la mezcla.',
    learning: 'Piensa en gramos de soluto por cada 100 g de solucion.',
    fields: [
      { name: 'soluteMassGrams', label: 'Masa de soluto', placeholder: '12.5', unit: 'g' },
      { name: 'solutionMassGrams', label: 'Masa de solucion', placeholder: '250', unit: 'g' },
      { name: 'percent', label: 'Concentracion', placeholder: '5', unit: '% m/m' },
    ],
    theory: {
      definition: 'Compara la masa del soluto con la masa total de la solucion.',
      useCase: 'Jarabes, pomadas, aleaciones y soluciones donde importa la proporcion en masa.',
      avoidUse: 'No es la opcion natural si el dato principal del problema es volumen.',
      difference: 'A diferencia de % m/v, aqui tanto numerador como denominador son magnitudes de masa.',
      clue: 'Si el enunciado entrega gramos del soluto y gramos de la solucion, esta suele ser la unidad adecuada.',
      commonMistake: 'Confundir masa de solucion con masa de solvente.',
      summary: 'Siempre se interpreta sobre 100 g de solucion final.',
    },
  },
  {
    id: 'mass-volume',
    shortLabel: '% m/v',
    title: 'Porcentaje masa / volumen',
    tagline: 'Expresa cuantos gramos de soluto hay en 100 mL de solucion.',
    formula: '% m/v = (masa de soluto / volumen de solucion) * 100',
    description: 'Muy usado en soluciones preparadas por volumen final y masa pesada de soluto.',
    learning: 'Piensa en gramos por cada 100 mL de solucion.',
    fields: [
      { name: 'soluteMassGrams', label: 'Masa de soluto', placeholder: '5', unit: 'g' },
      { name: 'solutionVolumeMilliliters', label: 'Volumen de solucion', placeholder: '250', unit: 'mL' },
      { name: 'percent', label: 'Concentracion', placeholder: '2', unit: '% m/v' },
    ],
    theory: {
      definition: 'Relaciona masa de soluto con volumen total de solucion.',
      useCase: 'Soluciones acuosas, sueros, reactivos y formulaciones preparadas hasta un volumen final.',
      avoidUse: 'No debe confundirse con % m/m cuando el denominador es masa y no volumen.',
      difference: 'El denominador es volumen de solucion, no masa de solucion.',
      clue: 'Si el problema habla de gramos en cierto volumen final, piensa primero en % m/v.',
      commonMistake: 'Tomar el volumen del solvente agregado como si fuera el volumen final de la solucion.',
      summary: 'Un 4% m/v significa 4 g de soluto en 100 mL de solucion.',
    },
  },
  {
    id: 'volume-volume',
    shortLabel: '% v/v',
    title: 'Porcentaje volumen / volumen',
    tagline: 'Mide la proporcion volumetrica de un liquido dentro de una mezcla.',
    formula: '% v/v = (volumen de soluto / volumen de solucion) * 100',
    description: 'Es habitual en mezclas liquidas como alcohol en agua u otras formulaciones liquidas.',
    learning: 'Piensa en mililitros de un componente por cada 100 mL de solucion.',
    fields: [
      { name: 'soluteVolumeMilliliters', label: 'Volumen de soluto', placeholder: '25', unit: 'mL' },
      { name: 'solutionVolumeMilliliters', label: 'Volumen de solucion', placeholder: '100', unit: 'mL' },
      { name: 'percent', label: 'Concentracion', placeholder: '25', unit: '% v/v' },
    ],
    theory: {
      definition: 'Compara el volumen del componente con el volumen total de la mezcla.',
      useCase: 'Bebidas, desinfectantes, mezclas de solventes y soluciones liquidas.',
      avoidUse: 'No es la unidad adecuada si el soluto se mide por masa.',
      difference: 'A diferencia de % m/v, aqui tanto el numerador como el denominador son volumenes.',
      clue: 'Si el enunciado da mL de liquidos mezclados, revisa si corresponde % v/v.',
      commonMistake: 'Olvidar que el volumen relevante es el volumen final de la solucion.',
      summary: 'Un 30% v/v equivale a 30 mL de soluto por cada 100 mL de mezcla.',
    },
  },
  {
    id: 'ppm',
    shortLabel: 'ppm',
    title: 'Partes por millon',
    tagline: 'Permite expresar concentraciones muy bajas de forma practica.',
    formula: 'ppm ~= mg de soluto / L de solucion',
    description: 'En soluciones acuosas diluidas se aproxima a mg/L y resulta muy util en analisis ambiental y de calidad.',
    learning: 'Piensa en miligramos de soluto por litro cuando la solucion es diluida.',
    fields: [
      { name: 'soluteMassMilligrams', label: 'Masa de soluto', placeholder: '3.2', unit: 'mg' },
      { name: 'solutionVolumeLiters', label: 'Volumen de solucion', placeholder: '1.5', unit: 'L' },
      { name: 'ppm', label: 'Concentracion', placeholder: '2.13', unit: 'ppm' },
    ],
    theory: {
      definition: 'Representa una parte de soluto por cada millon de partes de solucion.',
      useCase: 'Control de agua potable, contaminantes, trazas de sales y analisis ambientales.',
      avoidUse: 'No conviene usar la aproximacion mg/L = ppm fuera de soluciones diluidas comparables al agua.',
      difference: 'Se reserva para concentraciones pequenas donde porcentajes resultarian poco practicos.',
      clue: 'Si el problema habla de trazas o concentraciones muy bajas, ppm es candidata natural.',
      commonMistake: 'Aplicar sin justificar la equivalencia ppm = mg/L en sistemas no diluidos.',
      summary: 'En agua diluida, 1 ppm se interpreta aproximadamente como 1 mg/L.',
    },
  },
  {
    id: 'molarity',
    shortLabel: 'M',
    title: 'Molaridad',
    tagline: 'Expresa moles de soluto por litro de solucion.',
    formula: 'M = n / V y n = masa / masa molar',
    description: 'Es la unidad central para preparacion de soluciones y calculos estequiometricos.',
    learning: 'Piensa en cuantos moles de soluto hay en 1 L de solucion.',
    fields: [
      { name: 'molarityMolPerL', label: 'Molaridad', placeholder: '0.5', unit: 'mol/L' },
      { name: 'massSoluteGrams', label: 'Masa de soluto', placeholder: '24.5', unit: 'g' },
      { name: 'molarMassGramsPerMol', label: 'Masa molar', placeholder: '58.44', unit: 'g/mol' },
      { name: 'solutionVolumeLiters', label: 'Volumen de solucion', placeholder: '1', unit: 'L' },
    ],
    theory: {
      definition: 'Relaciona la cantidad de sustancia del soluto con el volumen final de la solucion.',
      useCase: 'Preparacion de reactivos, titulaciones y reacciones en solucion.',
      avoidUse: 'No es la mejor descripcion cuando solo se quiere porcentaje sin pasar por moles.',
      difference: 'Necesita masa molar para conectar gramos con moles.',
      clue: 'Si el problema menciona mol por litro o preparacion de soluciones patron, piensa en molaridad.',
      commonMistake: 'Usar mL sin convertir a L.',
      summary: 'Siempre usa volumen final de solucion expresado en litros.',
    },
  },
  {
    id: 'normality',
    shortLabel: 'N',
    title: 'Normalidad',
    tagline: 'Expresa equivalentes quimicos por litro de solucion.',
    formula: 'N = eq / V y eq = (masa / masa molar) * factor de equivalencia',
    description: 'Es especialmente util cuando la reaccion depende de protones, electrones o cargas intercambiadas.',
    learning: 'Piensa en equivalentes por litro, no solo en moles por litro.',
    fields: [
      { name: 'normalityEqPerL', label: 'Normalidad', placeholder: '1', unit: 'eq/L' },
      { name: 'massSoluteGrams', label: 'Masa de soluto', placeholder: '49', unit: 'g' },
      { name: 'molarMassGramsPerMol', label: 'Masa molar', placeholder: '98', unit: 'g/mol' },
      { name: 'equivalenceFactor', label: 'Factor de equivalencia', placeholder: '2', unit: 'n' },
      { name: 'solutionVolumeLiters', label: 'Volumen de solucion', placeholder: '1', unit: 'L' },
    ],
    theory: {
      definition: 'Relaciona los equivalentes quimicos del soluto con el volumen de la solucion.',
      useCase: 'Valoraciones acido-base, reacciones redox y procesos de precipitacion.',
      avoidUse: 'No debe aplicarse sin definir primero el contexto de reaccion y el factor de equivalencia.',
      difference: 'A diferencia de la molaridad, depende del rol quimico del soluto en la reaccion.',
      clue: 'Si el problema habla de equivalentes, protones cedidos o electrones transferidos, piensa en normalidad.',
      commonMistake: 'Usar el mismo factor de equivalencia en reacciones distintas.',
      summary: 'La normalidad solo tiene sentido cuando el contexto reactivo esta claro.',
    },
  },
  {
    id: 'mole-fraction',
    shortLabel: 'X',
    title: 'Fraccion molar',
    tagline: 'Mide la participacion relativa de un componente en el total de moles.',
    formula: 'X_i = n_i / n_total',
    description: 'Es una forma elegante de describir composicion, especialmente en mezclas y equilibrio.',
    learning: 'Piensa en la proporcion de moles de un componente respecto al total.',
    fields: [
      { name: 'moleFraction', label: 'Fraccion molar del componente', placeholder: '0.35', unit: 'X' },
      { name: 'molesComponent', label: 'Moles del componente', placeholder: '1.2', unit: 'mol' },
      { name: 'molesOther', label: 'Moles del resto de la mezcla', placeholder: '2.3', unit: 'mol' },
    ],
    theory: {
      definition: 'Expresa la proporcion de moles de un componente frente al total del sistema.',
      useCase: 'Mezclas de gases, soluciones ideales y diagramas de fase.',
      avoidUse: 'No es la unidad mas directa si el problema solo trabaja con porcentajes en masa o volumen.',
      difference: 'Es adimensional y la suma de todas las fracciones molares del sistema es 1.',
      clue: 'Si te piden composicion relativa basada en moles, esta es la unidad correcta.',
      commonMistake: 'Olvidar sumar todos los moles antes de dividir.',
      summary: 'No tiene unidad y siempre queda entre 0 y 1.',
    },
  },
];
