export const exercises = [
  {
    id: 'mm-01',
    unit: 'mass-mass',
    difficulty: 'basico',
    title: 'Salmuera al 12% m/m',
    prompt: 'Una solucion contiene 18 g de NaCl y 132 g de agua. Calcula el porcentaje masa/masa de la solucion.',
    steps: [
      { title: '1. Identificar datos', explanation: 'Se conocen masa de soluto y masa de solvente.' },
      { title: '2. Hallar masa total', explanation: 'masa de solucion = 18 + 132 = 150 g' },
      { title: '3. Sustituir', explanation: '% m/m = (18 / 150) * 100 = 12%' },
    ],
    answer: 'La solucion tiene 12% m/m.',
    takeaway: 'Primero reconstruye la masa total de la solucion.',
  },
  {
    id: 'mm-02',
    unit: 'mass-mass',
    difficulty: 'intermedio',
    title: 'Jarabe de sacarosa',
    prompt: 'Se desea preparar 250 g de una solucion al 8% m/m. Calcula la masa de sacarosa necesaria.',
    steps: [
      { title: '1. Reconocer el despeje', explanation: 'Se busca masa de soluto a partir del porcentaje y la masa total.' },
      { title: '2. Sustituir', explanation: 'masa de soluto = (8 / 100) * 250 = 20 g' },
      { title: '3. Interpretar', explanation: 'Cada 250 g de solucion deben contener 20 g de sacarosa.' },
    ],
    answer: 'Se requieren 20 g de sacarosa.',
    takeaway: 'En % m/m el referente siempre es la masa total de la solucion.',
  },
  {
    id: 'mv-01',
    unit: 'mass-volume',
    difficulty: 'basico',
    title: 'Solucion glucosada',
    prompt: 'Se disuelven 7.5 g de glucosa hasta completar 150 mL de solucion. Calcula el % m/v.',
    steps: [
      { title: '1. Formula', explanation: '% m/v = (masa / volumen) * 100' },
      { title: '2. Sustituir', explanation: '% m/v = (7.5 / 150) * 100 = 5%' },
      { title: '3. Interpretar', explanation: 'La solucion contiene 5 g de glucosa por cada 100 mL.' },
    ],
    answer: 'La concentracion es 5% m/v.',
    takeaway: 'En % m/v el volumen debe ser volumen final de solucion.',
  },
  {
    id: 'mv-02',
    unit: 'mass-volume',
    difficulty: 'intermedio',
    title: 'Preparacion de salina',
    prompt: 'Cuantos gramos de NaCl se necesitan para preparar 500 mL de solucion al 0.9% m/v?',
    steps: [
      { title: '1. Despejar', explanation: 'masa = (% m/v * volumen) / 100' },
      { title: '2. Sustituir', explanation: 'masa = (0.9 * 500) / 100 = 4.5 g' },
      { title: '3. Concluir', explanation: 'Se pesan 4.5 g y se completa hasta 500 mL.' },
    ],
    answer: 'Se necesitan 4.5 g de NaCl.',
    takeaway: 'El porcentaje se refiere a gramos por 100 mL.',
  },
  {
    id: 'vv-01',
    unit: 'volume-volume',
    difficulty: 'basico',
    title: 'Alcohol al 70%',
    prompt: 'Una mezcla contiene 70 mL de etanol en 100 mL de solucion. Calcula el % v/v.',
    steps: [
      { title: '1. Formula', explanation: '% v/v = (volumen de soluto / volumen de solucion) * 100' },
      { title: '2. Sustituir', explanation: '% v/v = (70 / 100) * 100 = 70%' },
      { title: '3. Interpretar', explanation: 'Hay 70 mL de etanol por cada 100 mL de mezcla.' },
    ],
    answer: 'La mezcla es 70% v/v.',
    takeaway: 'Usa esta unidad cuando ambos datos principales son volumenes.',
  },
  {
    id: 'vv-02',
    unit: 'volume-volume',
    difficulty: 'intermedio',
    title: 'Preparacion de mezcla liquida',
    prompt: 'Cuantos mililitros de acetona se necesitan para preparar 250 mL de una mezcla al 12% v/v?',
    steps: [
      { title: '1. Despejar', explanation: 'volumen de soluto = (% v/v * volumen total) / 100' },
      { title: '2. Sustituir', explanation: 'volumen de soluto = (12 * 250) / 100 = 30 mL' },
      { title: '3. Interpretar', explanation: 'Los otros 220 mL corresponden al resto de la mezcla.' },
    ],
    answer: 'Se necesitan 30 mL de acetona.',
    takeaway: 'No olvides que el volumen total es el volumen final de la solucion.',
  },
  {
    id: 'ppm-01',
    unit: 'ppm',
    difficulty: 'basico',
    title: 'Cloruros en agua',
    prompt: 'Una muestra de agua contiene 4 mg de cloruros en 2 L. Calcula la concentracion en ppm.',
    steps: [
      { title: '1. Aproximacion usada', explanation: 'Para agua diluida, ppm ~= mg/L.' },
      { title: '2. Sustituir', explanation: 'ppm ~= 4 / 2 = 2' },
      { title: '3. Interpretar', explanation: 'La muestra contiene aproximadamente 2 mg/L.' },
    ],
    answer: 'La concentracion es aproximadamente 2 ppm.',
    takeaway: 'Aclara siempre la aproximacion cuando trabajes con ppm.',
  },
  {
    id: 'ppm-02',
    unit: 'ppm',
    difficulty: 'intermedio',
    title: 'Muestra ambiental',
    prompt: 'Cuantos miligramos de soluto hay en 3.5 L de una solucion de 1.8 ppm?',
    steps: [
      { title: '1. Despejar', explanation: 'masa = ppm * volumen' },
      { title: '2. Sustituir', explanation: 'masa = 1.8 * 3.5 = 6.3 mg' },
      { title: '3. Interpretar', explanation: 'Ese valor representa la masa total disuelta en la muestra.' },
    ],
    answer: 'Hay 6.3 mg de soluto.',
    takeaway: 'En agua diluida puedes pensar ppm como mg/L.',
  },
  {
    id: 'molarity-01',
    unit: 'molarity',
    difficulty: 'basico',
    title: 'NaCl 0.5 M',
    prompt: 'Calcula la molaridad de una solucion preparada con 29.22 g de NaCl en 1 L. Usa masa molar 58.44 g/mol.',
    steps: [
      { title: '1. Convertir a moles', explanation: 'n = 29.22 / 58.44 = 0.5 mol' },
      { title: '2. Calcular molaridad', explanation: 'M = 0.5 / 1 = 0.5 mol/L' },
      { title: '3. Interpretar', explanation: 'La solucion contiene medio mol por litro.' },
    ],
    answer: 'La molaridad es 0.5 M.',
    takeaway: 'En molaridad, el volumen siempre va en litros.',
  },
  {
    id: 'molarity-02',
    unit: 'molarity',
    difficulty: 'intermedio',
    title: 'Preparacion de HCl',
    prompt: 'Cuantos gramos de HCl necesitas para preparar 750 mL de una solucion 0.20 M? Usa masa molar 36.46 g/mol.',
    steps: [
      { title: '1. Convertir volumen', explanation: '750 mL = 0.750 L' },
      { title: '2. Hallar moles', explanation: 'n = 0.20 * 0.750 = 0.150 mol' },
      { title: '3. Pasar a masa', explanation: 'masa = 0.150 * 36.46 = 5.469 g' },
    ],
    answer: 'Se necesitan 5.469 g de HCl.',
    takeaway: 'No mezcles mL con la formula de molaridad sin convertir.',
  },
  {
    id: 'normality-01',
    unit: 'normality',
    difficulty: 'basico',
    title: 'Acido sulfurico 1 N',
    prompt: 'Calcula la normalidad de una solucion preparada con 49 g de H2SO4 en 1 L. Usa masa molar 98 g/mol y factor 2.',
    steps: [
      { title: '1. Calcular equivalentes', explanation: 'eq = (49 / 98) * 2 = 1 eq' },
      { title: '2. Aplicar definicion', explanation: 'N = 1 / 1 = 1 eq/L' },
      { title: '3. Interpretar', explanation: 'La solucion aporta un equivalente por litro.' },
    ],
    answer: 'La normalidad es 1 N.',
    takeaway: 'La normalidad depende del factor de equivalencia del proceso considerado.',
  },
  {
    id: 'normality-02',
    unit: 'normality',
    difficulty: 'intermedio',
    title: 'Preparacion de base',
    prompt: 'Cuantos gramos de Ca(OH)2 se necesitan para preparar 500 mL de solucion 0.40 N? Usa masa molar 74.09 g/mol y factor 2.',
    steps: [
      { title: '1. Hallar equivalentes', explanation: 'eq = 0.40 * 0.500 = 0.20 eq' },
      { title: '2. Convertir a masa', explanation: 'masa = (0.20 * 74.09) / 2 = 7.409 g' },
      { title: '3. Interpretar', explanation: 'Esa masa se lleva a un volumen final de 500 mL.' },
    ],
    answer: 'Se necesitan 7.409 g de Ca(OH)2.',
    takeaway: 'Primero piensa en equivalentes y luego vuelve a gramos.',
  },
  {
    id: 'x-01',
    unit: 'mole-fraction',
    difficulty: 'basico',
    title: 'Mezcla etanol-agua',
    prompt: 'Una mezcla contiene 2.0 mol de etanol y 3.0 mol de agua. Calcula la fraccion molar del etanol.',
    steps: [
      { title: '1. Sumar moles', explanation: 'n_total = 2.0 + 3.0 = 5.0 mol' },
      { title: '2. Aplicar formula', explanation: 'X = 2.0 / 5.0 = 0.40' },
      { title: '3. Interpretar', explanation: 'El etanol representa el 40% de los moles.' },
    ],
    answer: 'La fraccion molar del etanol es 0.40.',
    takeaway: 'La suma de fracciones molares del sistema debe ser 1.',
  },
  {
    id: 'x-02',
    unit: 'mole-fraction',
    difficulty: 'intermedio',
    title: 'Componente faltante',
    prompt: 'Una mezcla binaria tiene fraccion molar de acetona 0.25 y contiene 6.0 mol del otro componente. Calcula los moles de acetona.',
    steps: [
      { title: '1. Despejar', explanation: 'n_i = (X_i * n_j) / (1 - X_i)' },
      { title: '2. Sustituir', explanation: 'n_i = (0.25 * 6.0) / 0.75 = 2.0 mol' },
      { title: '3. Verificar', explanation: '2.0 / (2.0 + 6.0) = 0.25' },
    ],
    answer: 'La mezcla contiene 2.0 mol de acetona.',
    takeaway: 'En problemas inversos conviene despejar antes de sustituir.',
  },
];
